---
title: "demogparhic"
author: "Aki"
date: "2/14/2024"
output: html_document
---
---
title: "ACNP"
output: html_document
date: "2023-02-16"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#MDD only: Pre Post
```{r}
library(readxl)
library(dplyr)
library(ggplot2)

dat1 <- read.csv('./data/demo.csv')
dat2 <- read.csv('./data/MADRS.csv')
dat3 <- read.csv('./data/BSRI.csv')
dat4 <- read.csv("./data/PANAS.csv")
dat6 <- read.csv("./data/RRS.csv")

dat6 <- dat6 %>%
mutate(RRS_T=(rrs_1+rrs_2+rrs_3+rrs_4+rrs_5+rrs_6+rrs_7+rrs_8+rrs_9+rrs_10+rrs_11+rrs_12+rrs_13+rrs_14+rrs_15+rrs_16+rrs_17+rrs_18+rrs_19+rrs_20+rrs_21+rrs_22),
      RRS_R=(rrs_7+rrs_11+rrs_12+rrs_20+rrs_21),
      RRS_B=(rrs_5+rrs_10+rrs_13+rrs_15+rrs_16),
      RRS_D=(rrs_1+rrs_2+rrs_3+rrs_4+rrs_6+rrs_8+rrs_9+rrs_14+rrs_17+rrs_18+rrs_19+ rrs_22))

#Remove the empty rows
dat1 <- dat1[!is.na(dat1$SID),]

# Rename the column
dat2 <- rename(dat2, SID = record_id)
dat3 <- rename(dat3, SID = record_id)
dat4 <- rename(dat4, SID = record_id)
dat6 <- rename(dat6, SID = record_id)



dat <- merge(dat1, dat2, by.x = "SID")
dat <- left_join(dat, dat3, by.x = "SID")
dat <- left_join(dat, dat4, by.x = "SID")
dat <- left_join(dat, dat6, by.x = "SID")
#dat <- dat %>% filter(!(SID %in% c("AV503", "AW090", "BB898","BM110", "BR717", "BU113", "BU206", "BU640", "BU693", "BU894")))
#dat <- dat %>% filter(!(SID %in% c("BM110", "BR717", "BU113", "BU206", "BU640", "BU693", "BU894")))
#write.csv(dat, 'test.csv')

dat <- dat %>%
    mutate(redcap_event_name = ifelse(Order == "A",
                                      case_when(
                                          redcap_event_name == "visit_1_day_1_pre_arm_1" ~ "FUS_pre",
                                          redcap_event_name == "visit_1_day_1_post_arm_1" ~ "FUS_post",
                                          redcap_event_name == "visit_3_day144_pre_arm_1" ~ "Sham_pre",
                                          redcap_event_name == "visit_3_day144_pos_arm_1" ~ "Sham_post",
                                          redcap_event_name == "screening_day_7_to_arm_1" ~ "Screening",
                                          redcap_event_name == "visit_2_day74_arm_1" ~ "V2",
                                          redcap_event_name == "visit_4_day214_arm_1" ~ "V4",
                                          TRUE ~ redcap_event_name),
                                      ifelse(Order == "B",
                                             case_when(
                                                 redcap_event_name == "visit_1_day_1_pre_arm_1" ~ "Sham_pre",
                                                 redcap_event_name == "visit_1_day_1_post_arm_1" ~ "Sham_post",
                                                 redcap_event_name == "visit_3_day144_pre_arm_1" ~ "FUS_pre",
                                                 redcap_event_name == "visit_3_day144_pos_arm_1" ~ "FUS_post",
                                                 redcap_event_name == "screening_day_7_to_arm_1" ~ "Screening",
                                                 redcap_event_name == "visit_2_day74_arm_1" ~ "V2",
                                                 redcap_event_name == "visit_4_day214_arm_1" ~ "V4",
                                                 TRUE ~ redcap_event_name),
                                             redcap_event_name)))

# Change the factor order
dat$redcap_event_name <- factor(dat$redcap_event_name, levels = c("Screening", "FUS_pre", "FUS_post", "V2", "Sham_pre", "Sham_post", "V4"))
dat$Group <- factor(dat$Group, levels = c("High", "Low", "HC"))



#Remove V2, Screening, V4
#dat <- filter(dat, redcap_event_name != "V2")
#dat <- filter(dat, redcap_event_name != "Screening")
#dat <- filter(dat, redcap_event_name != "V4")            



# Create a new group where High and Low are combined into MDD
dat$Group2 <- ifelse(dat$Group %in% c("High", "Low"), "MDD", "HC")

dat$Group2 <- factor(dat$Group2, levels = c("MDD", "HC"))

# Creat a new time where pre and post are combined regardless of FUS or Sham
dat$redcap_event_name2 <- ifelse(dat$redcap_event_name %in% c("FUS_pre", "Sham_pre"), "Pre", "Post")

dat$redcap_event_name2 <- factor(dat$redcap_event_name2, levels = c("Pre", "Post"))

#MDD ONLY
dat <- dat %>% filter(!(Group %in% c("HC")))

#Dat Screening 
dat_screening <- filter(dat, redcap_event_name == "Screening")

#Dat 

```



```{r chi square, massage=FALSE}

table(dat_screening$Sex)
table(dat$Medicated)
table(dat$Handedness)
table(dat$Episode)
table(dat$Anx_dxs)
table(dat$Sedative)


```

```{r table 1}
#library(table1)
library(devtools)
#install_github("emwozniak/Table1", force=TRUE)
library(Table1)
make.table(dat=dat_screening, cont.varlist=c("Age", "bsri_score", "madrs_score", "RRS_T", "RRS_B", "RRS_D", "RRS_R","panasx_negaffect_score",  "panasx_posaffect_score", "panasx_fear_score", "panasx_hostility_score",  "panasx_guilt_score", "panasx_sadness_score","panasx_joviality_score",  "panasx_selfassurance_score", "panasx_attentiveness_score", "panasx_shyness_score",  "panasx_fatigue_score", "panasx_serenity_score",
  "panasx_surprise_score"))

library(tableone)
# Define the list of continuous variables
cont_varlist <- c("Age", "bsri_score", "madrs_score", "RRS_T", "RRS_B", "RRS_D", "RRS_R",
                  "panasx_negaffect_score", "panasx_posaffect_score", "panasx_fear_score", 
                  "panasx_hostility_score", "panasx_guilt_score", "panasx_sadness_score",
                  "panasx_joviality_score", "panasx_selfassurance_score", "panasx_attentiveness_score", 
                  "panasx_shyness_score", "panasx_fatigue_score", "panasx_serenity_score", 
                  "panasx_surprise_score")

# Create Table 1
table1 <- CreateTableOne(vars = cont_varlist, data = dat_screening)

# Print the table to the console
print(table1)



table1 <- CreateTableOne(vars = cont_varlist, strata = "Group2", data = dat_screening)
#table1 <- CreateTableOne(vars = cont_varlist, data = dat_screening, 
#                         nonnormal = cont_varlist)
# Print the table to the console
print(table1)

```

```{r t-test}

#t-test
dflist <- c("Age", "RRS_total", "RRS_reflection", "RRS_brooding", "RRS_depression", "RRS_brdep", "MADRS", 'HAMA',"PHQ","STAI", "motion_View1","motion_NF1", "motion_NF2", "motion_NF3", "motion_View2", "ave_motion_NF")

for (i in dflist) {
    X <- dat[,i]
    df<-data.frame(group=factor(dat$Group),X)
    res1<-t.test(eval(parse(text=i))~group,data=df, var.equal=TRUE)
    cat(i, "T-test", "\n")
    print(res1)
    cat("------END------", "\n")
}


```






